import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { gzipSync } from 'node:zlib'
import { transform } from 'lightningcss'
import {
  addNotProseGuard,
  browserTargets,
  LAYER_ORDER,
  pinLayerOrder,
  runBuild,
  transformStyleRules,
} from '../../scripts/css-lib.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, 'dist')
const targets = browserTargets()

const banner = `/*!
 * @cloudensis/prose - typography for Japanese-first long-form articles.
 * Generated by packages/prose/build.mjs - do not edit dist/ by hand.
 * Edit packages/prose/src/prose.css instead.
 */`

await runBuild(async () => {
  const source = await readFile(join(here, 'src', 'prose.css'), 'utf8')

  // 5.3: the `.not-prose` exclusion is applied mechanically to every selector
  // here, never by hand in the source file.
  const guarded = transformStyleRules(source, addNotProseGuard)

  const wrapped = `${banner}
${LAYER_ORDER}

@layer cds.prose {
${guarded}
}
`

  const compile = (minify) =>
    pinLayerOrder(
      transform({
        filename: 'prose.css',
        code: Buffer.from(wrapped),
        targets,
        minify,
      }).code,
    )

  const readable = compile(false)
  const minified = compile(true)

  await mkdir(dist, { recursive: true })
  await writeFile(join(dist, 'prose.css'), readable)
  await writeFile(join(dist, 'prose.min.css'), minified)

  const raw = Buffer.byteLength(minified)
  const gzip = gzipSync(Buffer.from(minified)).length
  console.log(
    `@cloudensis/prose: built dist/prose.css, dist/prose.min.css ` +
      `(${(raw / 1024).toFixed(1)} KB raw, ${(gzip / 1024).toFixed(1)} KB gzip)`,
  )
}, [join(here, 'src')])
