// The single source of truth for @cloudensis/tokens.
//
// 4.3 requires the same values to appear in four different blocks (light
// default, OS-dark, explicit dark, explicit light). They are written once here
// and the four blocks are generated by build.mjs - hand-duplicating them is how
// light and dark drift apart.

/** Tokens that do not change between light and dark. */
export const base = {
  'font-sans': [
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    '"Segoe UI"',
    'Roboto',
    '"Helvetica Neue"',
    'Arial',
    // Japanese-first: the CJK faces have to come before the generic fallback
    // or Windows/Linux pick something with no kana coverage. (5.8)
    '"Hiragino Sans"',
    '"Hiragino Kaku Gothic ProN"',
    '"Noto Sans JP"',
    'Meiryo',
    'sans-serif',
  ].join(', '),
  'font-mono': [
    'ui-monospace',
    'SFMono-Regular',
    'Menlo',
    'Consolas',
    '"Liberation Mono"',
    '"Noto Sans Mono CJK JP"',
    'monospace',
  ].join(', '),

  'radius-sm': '0.25rem',
  'radius-md': '0.5rem',
  'radius-lg': '0.75rem',

  'space-1': '0.25rem',
  'space-2': '0.5rem',
  'space-3': '0.75rem',
  'space-4': '1rem',
  'space-5': '1.25rem',
  'space-6': '1.5rem',
  'space-7': '2rem',
  'space-8': '2.5rem',
  'space-9': '3rem',
  'space-10': '4rem',
  'space-11': '5rem',
  'space-12': '6rem',
}

/**
 * Tokens that flip with the colour scheme. Every key must exist in both maps;
 * build.mjs fails the build if they diverge.
 *
 * TODO(brand): `accent` / `accent-hover` are a neutral blue placeholder. Swap
 * them for the Cloudensis brand colour once it is decided. Nothing else in the
 * repository hard-codes a link colour, so this is the only edit needed.
 */
export const light = {
  'color-scheme': 'light',

  'color-bg': '#ffffff',
  'color-bg-subtle': '#f4f4f5',

  'color-fg': '#3f3f46',
  'color-fg-muted': '#71717a',

  'color-accent': '#2563eb',
  'color-accent-hover': '#1d4ed8',

  'color-border': '#d4d4d8',
  'color-border-subtle': '#e4e4e7',

  'color-success': '#15803d',
  'color-warn': '#b45309',
  'color-danger': '#b91c1c',
  'color-info': '#1d4ed8',

  'color-code-fg': '#3f3f46',
  'color-code-bg': '#f4f4f5',

  'shadow-sm': '0 1px 2px 0 rgba(24, 24, 27, 0.06), 0 1px 3px 0 rgba(24, 24, 27, 0.1)',
  'shadow-md': '0 2px 4px -2px rgba(24, 24, 27, 0.08), 0 4px 12px -2px rgba(24, 24, 27, 0.12)',
}

export const dark = {
  'color-scheme': 'dark',

  'color-bg': '#18181b',
  'color-bg-subtle': '#27272a',

  'color-fg': '#d4d4d8',
  'color-fg-muted': '#a1a1aa',

  'color-accent': '#60a5fa',
  'color-accent-hover': '#93c5fd',

  'color-border': '#52525b',
  'color-border-subtle': '#3f3f46',

  'color-success': '#4ade80',
  'color-warn': '#fbbf24',
  'color-danger': '#f87171',
  'color-info': '#60a5fa',

  'color-code-fg': '#e4e4e7',
  'color-code-bg': '#27272a',

  'shadow-sm': '0 1px 2px 0 rgba(0, 0, 0, 0.5), 0 1px 3px 0 rgba(0, 0, 0, 0.4)',
  'shadow-md': '0 2px 4px -2px rgba(0, 0, 0, 0.5), 0 4px 12px -2px rgba(0, 0, 0, 0.45)',
}
