import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'
import { transform } from 'lightningcss'
import { browserTargets, pinLayerOrder, runBuild } from '../../scripts/css-lib.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, 'dist')
const source = pathToFileURL(join(here, 'src', 'tokens.mjs')).href
const targets = browserTargets()

const banner = `/*!
 * @cloudensis/tokens - design tokens as CSS custom properties.
 * Generated by packages/tokens/build.mjs - do not edit dist/ by hand.
 * Edit packages/tokens/src/tokens.mjs instead.
 */`

const decls = (map, indent) =>
  Object.entries(map)
    .map(([name, value]) => `${indent}--cds-${name}: ${value};`)
    .join('\n')

function assertInSync(light, dark) {
  const problems = [
    ...Object.keys(light).filter((k) => !(k in dark)).map((k) => `dark is missing ${k}`),
    ...Object.keys(dark).filter((k) => !(k in light)).map((k) => `light is missing ${k}`),
  ]
  if (problems.length > 0) {
    throw new Error(`light/dark token sets are out of sync:\n  ${problems.join('\n  ')}`)
  }
}

/**
 * 4.3: the same values have to appear in four blocks. They are authored once
 * in src/tokens.mjs and expanded here.
 *
 * The order of the blocks is load-bearing. Specificity is deliberately flat, so
 * "an explicit choice beats the OS setting" rests purely on source order:
 * block 4 comes last, therefore `.light` always wins over a dark OS.
 */
function render({ base, light, dark }) {
  assertInSync(light, dark)
  return `${banner}
@layer cds.tokens, cds.prose, cds.ui;

@layer cds.tokens {
  /* 1. Light - the default, plus every scheme-independent token. */
  :root {
${decls(base, '    ')}

${decls(light, '    ')}
  }

  /* The only non-custom-property declaration in this package. It makes native
     widgets, form controls and scrollbars follow the token set. Override
     --cds-color-scheme to opt out. */
  :root {
    color-scheme: var(--cds-color-scheme);
  }

  /* 2. The OS prefers dark and nothing has explicitly asked for light. */
  @media (prefers-color-scheme: dark) {
    :root:not(.light):not([data-theme="light"]) {
${decls(dark, '      ')}
    }
  }

  /* 3. Explicit dark. Not pinned to :root, so any ancestor can flip a subtree. */
  .dark,
  [data-theme="dark"] {
${decls(dark, '    ')}
  }

  /* 4. Explicit light. Last, so a manual choice always beats the OS setting. */
  .light,
  [data-theme="light"] {
${decls(light, '    ')}
  }
}
`
}

await runBuild(async () => {
  const tokens = await import(`${source}?v=${Date.now()}`)
  const { code } = transform({
    filename: 'tokens.css',
    code: Buffer.from(render(tokens)),
    targets,
    minify: false,
  })
  await mkdir(dist, { recursive: true })
  await writeFile(join(dist, 'tokens.css'), pinLayerOrder(code))
  console.log('@cloudensis/tokens: built dist/tokens.css')
}, [join(here, 'src')])
