import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { transform } from 'lightningcss'
import { browserTargets, LAYER_ORDER, pinLayerOrder, runBuild } from '../../scripts/css-lib.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, 'dist')
const targets = browserTargets()

const banner = `/*!
 * @cloudensis/ui - component styles.
 * Generated by packages/ui/build.css.mjs - do not edit dist/ by hand.
 * Edit packages/ui/src/ui.css instead.
 */`

await runBuild(async () => {
  const source = await readFile(join(here, 'src', 'ui.css'), 'utf8')

  const wrapped = `${banner}
${LAYER_ORDER}

@layer cds.ui {
${source}
}
`

  const compile = (minify) =>
    pinLayerOrder(
      transform({ filename: 'ui.css', code: Buffer.from(wrapped), targets, minify }).code,
    )

  await mkdir(dist, { recursive: true })
  await writeFile(join(dist, 'ui.css'), compile(false))
  await writeFile(join(dist, 'ui.min.css'), compile(true))
  console.log('@cloudensis/ui: built dist/ui.css, dist/ui.min.css')
}, [join(here, 'src')])
